# Generated by Django 3.1.14 on 2022-12-17 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Time of creation of this object')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time of updation of this object')),
                ('is_active', models.BooleanField(default=True, help_text='Denotes if the object is active or not. Inactive objects behave similar to how a deleted object works.')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('system_user', models.OneToOneField(help_text='The django user linked to this user', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(is_active=True), fields=['is_active'], name='user_is_active'),
        ),
    ]
