# Generated by Django 3.1.14 on 2022-12-17 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='system_user',
            field=models.OneToOneField(help_text='The django user linked to this user', on_delete=django.db.models.deletion.PROTECT, related_name='todostack_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
