# Generated by Django 3.1.14 on 2022-12-17 19:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Time of creation of this object')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time of updation of this object')),
                ('is_active', models.BooleanField(default=True, help_text='Denotes if the object is active or not. Inactive objects behave similar to how a deleted object works.')),
                ('title', models.CharField(help_text='Represents the title of the todo item', max_length=200)),
                ('description', models.TextField(help_text='Represents the description of the todo item')),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0, help_text='Represents the priority of the todo item')),
                ('due_date', models.DateTimeField(blank=True, help_text='Represents the due date of the todo item.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Represents the date and time when the todo item was completed', null=True)),
                ('owner', models.ForeignKey(help_text='Owner of the todo item', on_delete=django.db.models.deletion.CASCADE, related_name='todo_items', to='accounts.user')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(condition=models.Q(is_active=True), fields=['is_active'], name='todoitem_is_active'),
        ),
    ]
